api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views


router = DefaultRouter()
router.register('users', views.UserViewSet)
router.register('groups', views.GroupViewSet)

router.register('model-prints', views.ModelPrintViewSet)
router.register('manufacturers', views.ManufacturerViewSet)
router.register('filament-rolls', views.FilamentRollViewSet)
router.register('filament-instances', views.FilamentInstanceViewSet)
router.register('filament-materials', views.FilamentMaterialViewSet)

urlpatterns = router.urls + [

]

prints/urls.py
from django.urls import path

from . import views

app_name = 'prints'
urlpatterns = [
    #================================================================
    ## `Manufacturer` Routes:
    path(
        'manufacturers/',
        views.ManufacturerListView.as_view(),
        name='manufacturers',
    ),
    path(
        'manufacturers/<int:pk>/',
        views.ManufacturerDetailView.as_view(),
        name='manufacturer_detail'
    ),
    path(
        'manufacturers/new/',
        views.ManufacturerCreateView.as_view(),
        name='manufacturer_new'
    ),
    path(
        'manufacturers/<int:pk>/edit/',
        views.ManufacturerUpdateView.as_view(),
        name='manufacturer_edit'
    ),
    path(
        'manufacturers/<int:pk>/delete/',
        views.ManufacturerDeleteView.as_view(),
        name='manufacturer_delete'
    ),
    #================================================================
    
    
    #================================================================
    ## `FilamentMaterial` Routes:
    path(
        'filament-materials/',
        views.FilamentMaterialListView.as_view(),
        name='filament_materials',
    ),
    path(
        'filament-materials/<int:pk>/',
        views.FilamentMaterialDetailView.as_view(),
        name='filament_material_detail'
    ),
    path(
        'filament-materials/new/',
        views.FilamentMaterialCreateView.as_view(),
        name='filament_material_new'
    ),
    path(
        'filament-materials/<int:pk>/edit/',
        views.FilamentMaterialUpdateView.as_view(),
        name='filament_material_edit'
    ),
    path(
        'ilament-materials/<int:pk>/delete/',
        views.FilamentMaterialDeleteView.as_view(),
        name='filament_material_delete'
    ),
    #================================================================


    #================================================================
    ## `FilamentRoll` Routes:
    path(
        'rolls/',
        views.FilamentRollListView.as_view(),
        name='rolls',
    ),
    path(
        'rolls/<int:pk>/',
        views.FilamentRollDetailView.as_view(),
        name='roll_detail'
    ),
    path(
        'rolls/new/',
        views.FilamentRollCreateView.as_view(),
        name='roll_new'
    ),
    path(
        'rolls/<int:pk>/edit/',
        views.FilamentRollUpdateView.as_view(),
        name='roll_edit'
    ),
    path(
        'rolls/<int:pk>/delete/',
        views.FilamentRollDeleteView.as_view(),
        name='roll_delete'
    ),
    #================================================================


    #================================================================
    ## `FilamentInstance` Routes:
    path(
        'filament-instances/',
        views.FilamentInstanceListView.as_view(),
        name='filament_instances',
    ),
    path(
        'filament-instances/<int:pk>/',
        views.FilamentInstanceDetailView.as_view(),
        name='filament_instance_detail'
    ),
    path(
        'filament-instances/new/',
        views.FilamentInstanceCreateView.as_view(),
        name='filament_instance_new'
    ),
    path(
        'filament-instances/<int:pk>/edit/',
        views.FilamentInstanceUpdateView.as_view(),
        name='filament_instance_edit'
    ),
    path(
        'filament-instances/<int:pk>/delete/',
        views.FilamentInstanceDeleteView.as_view(),
        name='filament_instance_delete'
    ),
    #================================================================


    #================================================================
    ## `ModelPrint` Routes:
    path(
        'models/',
        views.ModelPrintListView.as_view(),
        name='models'
    ),
    path(
        'models/<int:pk>/',
        views.ModelPrintDetailView.as_view(),
        name='model_detail'
    ),
    path(
        'models/new/',
        views.new_model_print,
        name='model_new'
    ),
    path(
        'models/<int:pk>/edit/',
        views.ModelPrintUpdateView.as_view(),
        name='model_update'
    ),
    path(
        'models/<int:pk>/delete/',
        views.ModelPrintDeleteView.as_view(),
        name='model_delete'
    ),
    #================================================================


    #================================================================
    ## User Print Profile Routes:
    path(
        'user-print-profile/',
        views.UserPrintsProfileView.as_view(),
        name='user_print_profile'
    )
    #================================================================
]

prints/forms.py
from django import forms

from .models import FilamentRoll, Manufacturer


class CreateModelPrintForm(forms.Form):
    model_print_name = forms.CharField(
        label='Model Print Name',
        max_length=255,
    )
    grams_filament_consumed = forms.IntegerField(
        label="Filament Consumed",
        help_text='Units of grams (g)',
        min_value=0,
    )
    filament_roll_chosen = forms.ModelChoiceField(
        label='Filament Roll Chosen',
        help_text='Available Rolls',
        queryset=FilamentRoll.objects.all(),
    )


class CreateFilamentRollForm(forms.Form):
    manufacturer = forms.ModelChoiceField(
        label='Manufacturer',
        help_text='Available Manufacturers',
        queryset=Manufacturer.objects.all(),
    )
    material = forms.CharField(
        label='Material',
        max_length=255,
    )

prints/views.py
from django.urls import reverse_lazy
from django.urls import reverse

from django.views.generic import ListView
from django.views.generic import DetailView

from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import FormView
from django.views.generic.edit import FormMixin

from django.contrib import auth

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin

from django.http import HttpResponseRedirect
from django.http import HttpResponse

from django.shortcuts import render
from django.shortcuts import get_object_or_404

from django.forms.models import modelform_factory
import pprint

from prints.models import Manufacturer
from prints.models import FilamentMaterial
from prints.models import FilamentRoll
from prints.models import FilamentInstance
from prints.models import ModelPrint

from .forms import CreateModelPrintForm
from .forms import CreateFilamentRollForm


#================================================================
## `Manufacturer` Views:
class ManufacturerListView(LoginRequiredMixin, ListView):
    model = Manufacturer
    template_name = 'prints/manufacturer_list.html'


class ManufacturerDetailView(LoginRequiredMixin, DetailView):
    model = Manufacturer
    template_name = 'prints/manufacturer_detail.html'


class ManufacturerCreateView(LoginRequiredMixin, CreateView):
    model = Manufacturer
    template_name = 'prints/manufacturer_create.html'
    fields = [
        'name',
    ]


class ManufacturerUpdateView(LoginRequiredMixin, UpdateView):
    model = Manufacturer
    template_name = 'prints/manufacturer_edit.html'
    fields = [
        'name',
    ]


class ManufacturerDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Manufacturer
    template_name = 'prints/manufacturer_delete.html'
    success_url = reverse_lazy('prints:manufacturers')

    def test_func(self):
        """
        Allow delete view if `Manufacturer` instance has no related 
        `FilamentRoll` instances.
        """
        manufacturer = self.get_object()
        return not manufacturer.rolls.count()
#================================================================


#================================================================
## `FilamentMaterial` Views:
class FilamentMaterialListView(LoginRequiredMixin, ListView):
    model = FilamentMaterial
    template_name = 'prints/filament_material_list.html'


class FilamentMaterialDetailView(LoginRequiredMixin, DetailView):
    model = FilamentMaterial
    template_name = 'prints/filament_material_detail.html'


class FilamentMaterialCreateView(LoginRequiredMixin, CreateView):
    model = FilamentMaterial
    template_name = 'prints/filament_material_create.html'
    fields = [
        'METERS_PER_GRAM',
        'polymer_type',
    ]


class FilamentMaterialUpdateView(LoginRequiredMixin, UpdateView):
    model = FilamentMaterial
    template_name = 'prints/filament_material_edit.html'
    fields = [
        'METERS_PER_GRAM',
        'polymer_type',
    ]


class FilamentMaterialDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = FilamentMaterial
    template_name = 'prints/filament_material_delete.html'
    success_url = reverse_lazy('prints:filament_materials')

    def test_func(self):
        """
        Allow delete view if `FilamentMaterial` instance has no related 
        `FilamentRoll` instances.
        """
        filament_material = self.get_object()
        return not filament_material.rolls.count()
#================================================================


#================================================================
## `FilamentRoll` Views:
class FilamentRollListView(LoginRequiredMixin, ListView):
    model = FilamentRoll
    template_name = 'prints/filament_roll_list.html'


class FilamentRollDetailView(LoginRequiredMixin, DetailView):
    model = FilamentRoll
    template_name = 'prints/filament_roll_detail.html'


class FilamentRollCreateView(LoginRequiredMixin, CreateView):
    model = FilamentRoll
    template_name = 'prints/filament_roll_create.html'
    fields = [
        'manufacturer',
        'material',
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filament_materials'] = FilamentMaterial.objects.all()
        return context

    def form_valid(self, form):
        print('self.request.user: ', self.request.user)
        form.instance.owner = self.request.user
        return super().form_valid(form)


class FilamentRollUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = FilamentRoll
    template_name = 'prints/filament_roll_edit.html'
    fields = [
       'manufacturer',
       'material',
    ]

    def test_func(self):
        roll = self.get_object()
        print('roll: ', roll)
        return self.request.user == roll.owner


class FilamentRollDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = FilamentRoll
    template_name = 'prints/filament_roll_delete.html'
    success_url = reverse_lazy('prints:rolls')

    def test_func(self):
        roll = self.get_object()
        print('roll: ', roll)
        return self.request.user == roll.owner
#================================================================


#================================================================
## `FilamentInstance` Views:
class FilamentInstanceListView(LoginRequiredMixin, ListView):
    model = FilamentInstance
    template_name = 'prints/filament_instance_list.html'


class FilamentInstanceDetailView(LoginRequiredMixin, DetailView):
    model = FilamentInstance
    template_name = 'prints/filament_instance_detail.html'


class FilamentInstanceCreateView(LoginRequiredMixin, CreateView):
    model = FilamentInstance
    template_name = 'prints/filament_instance_create.html'
    fields = [
        'grams_filament_consumed',
        'filament_roll',
    ]


class FilamentInstanceUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = FilamentInstance
    template_name = 'prints/filament_instance_edit.html'
    fields = [
        'grams_filament_consumed',
        'filament_roll',
    ]

    def test_func(self):
        filament_instance = self.get_object()
        print('filament_instance: ', filament_instance)
        return self.request.user == filament_instance.filament_roll.owner


class FilamentInstanceDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = FilamentInstance
    template_name = 'prints/filament_instance_delete.html'
    success_url = reverse_lazy('prints:filament_instances')

    def test_func(self):
        filament_instance = self.get_object()
        print('filament_instance: ', filament_instance)
        print(f"FilamentInstance deletion possible: {not hasattr(filament_instance, 'print')}")
        return (
            # User is `FilamentRoll` `owner`:
            self.request.user == filament_instance.filament_roll.owner
            and
            # `FilamentInstance` instance has no associated `ModelPrint`s:
            not hasattr(filament_instance, 'print')
        )

#================================================================


#================================================================
## `ModelPrint` Views:
class ModelPrintListView(LoginRequiredMixin, ListView):
    """
    Class-based view, which inherits from `django.views.generic.list.ListView`, to provide list view of model `ModelPrint`.
    """
    model = ModelPrint
    template_name = 'prints/model_print_list.html'


class ModelPrintDetailView(LoginRequiredMixin, DetailView):
    """
    Class-based view, which inherits from `django.views.generic.detail.DetailView`, to provide detail view of model `ModelPrint`.
    """
    model = ModelPrint
    template_name = 'prints/model_print_detail.html'


def new_model_print(request):
    print("\n\n'new_model_print()' has been called:")
    
    if request.method == 'POST':
        filament_roll_id = request.POST.get('filament_roll_chosen')

        current_filament_roll = get_object_or_404(
            FilamentRoll,
            pk=filament_roll_id
        )
        current_filament_consumed = request.POST.get('grams_filament_consumed')
        new_filament_instance = FilamentInstance.objects.create(
            filament_roll=current_filament_roll,
            grams_filament_consumed=current_filament_consumed,
        )

        current_model_print_name = request.POST.get('model_print_name')
        current_user = auth.get_user(request)
        new_model_print = ModelPrint.objects.create(
            filament_instance=new_filament_instance,
            name=current_model_print_name,
            creator=current_user,
        )
        print('new_model_print: ', new_model_print)
        return HttpResponseRedirect(
            reverse('prints:model_detail', kwargs={ 'pk': new_model_print.id})
        )

    elif request.method == 'GET':
        create_model_print_form = CreateModelPrintForm()
        create_filament_roll_form = CreateFilamentRollForm()
        context = {
            'model_print_form': create_model_print_form,
            'filament_roll_form': create_filament_roll_form,
        }

        filament_rolls = FilamentRoll.objects.all()
        context['filament_rolls_in_template'] = filament_rolls

        print('context: ')
        pprint.pprint(context)
        return render(
            request,
            'prints/model_print_create.html',
            context
        )


class ModelPrintUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    Class-based view, which inherits from `LoginRequiredMixin`, `UserPassesTestMixin`, and `django.views.generic.UpdateView`. Allows users to update their own `ModelPrint` instances.
    """
    model = ModelPrint

prints/templates/prints/filament_instance_create.html
{% extends "base.html" %}

{% block title %}Print Tracker - New Filament Instance{% endblock %}

{% block content %}
<main>

    <h2>New Filament Instance</h1>
    <form action="{% url 'prints:filament_instance_new' %}" method="post">
        {% csrf_token %}
    
        {{ form.as_p }}
    
        <input type="submit" value="Create New Filament Instance" />
    </form>

</main>
{% endblock %}

prints/templates/prints/filament_instance_detail.html
{% extends "base.html" %}

{% block title %}Print Tracker - {{ filamentinstance }}{% endblock %}

{% block content %}
<main>

    <h2>Filament Instance: {{ filamentinstance }}</h2>
    {% if filamentinstance.filament_roll.owner == user %}
        <a href={% url 'prints:filament_instance_edit' filamentinstance.id %}>
            Edit Filament Instance
        </a><br>
    {% endif %}
    <dl>
        <dt>Associated Filament Roll</dt>
        <dd><a href={% url 'prints:roll_detail' filamentinstance.filament_roll.id %}>
            {{ filamentinstance.filament_roll }}
        </a></dd>
        <dt>Filament Consumed</dt>
        <dd>{{ filamentinstance.grams_filament_consumed }} grams</dd>
    </dl>
    {% if filamentinstance.print %}
        <dl>
            <dt>Associated Model Print</dt>
            <dd><a href={% url 'prints:model_detail' filamentinstance.print.id %}>
                {{ filamentinstance.print }}
            </a></dd>
        </dl>
    {% else %}
    <p>No associated Model Print</p>
    {% endif %}

</main>
{% endblock %}

prints/templates/prints/filament_material_delete.html
{% extends "base.html" %}

{% block title %}
    Print Tracker - Delete Filament Material: {{ filamentmaterial }}
{% endblock %}

{% block content %}
<main>

    <form action="" method="post">
        {% csrf_token %}
        <p>Do you really want to delete "{{ filamentmaterial }}"?</p>
        <input type="submit" value="Confirm Delete" />
    </form>

</main>
{% endblock %}

prints/templates/prints/filament_material_edit.html
{% extends "base.html" %}

{% block title %}Print Tracker - Edit: {{ filamentmaterial }}{% endblock %}

{% block content %}
    <main>

        {{ filamentmaterial }}<br>
        <a href={% url 'prints:filament_material_detail' filamentmaterial.id %}>
            Cancel Edit
        </a><br>

        {% if filamentmaterial.rolls.count == 0 %}
            <a href={% url 'prints:filament_material_delete' filamentmaterial.id %}>
                Delete Filament Material
            </a><br>
        {% else %}
            <p>
                Filament Material cannot be deleted since it is associated
                with at least one existing Filament Roll.
            </p>
        {% endif %}
        
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save changes to Filament Material" />
        </form>

    </main>
{% endblock %}

prints/templates/prints/filament_material_list.html
{% extends "base.html" %}

{% block title %}Print Tracker - Filament Materials{% endblock %}

{% block content %}
    <main class="flex-gallery">
    
        {% for filament_material in object_list %}
    
            <div class="flex-item item">

                <a href={% url 'prints:filament_material_detail' filament_material.id %}>
                    {{ filament_material }}
                </a>
                <dl>
                    <dt>Number of Rolls</dt>
                    <dd>{{ filament_material.rolls.count }}</dd>
                </dl>
            </div>
    
        {% endfor %}
    
    </main>
{% endblock %}

prints/templates/prints/filament_roll_create.html
{% extends "base.html" %}

{% block title %}Print Tracker - New 3D Filament Roll{% endblock %}

{% block content %}
<main>

    <h2>New Filament Roll</h1>
    <form action="{% url 'prints:roll_new' %}" method="post">
        {% csrf_token %}
    
        {{ form.as_p }}
    
        <input type="submit" value="Create New Filament Roll" />
    </form>

    <h3>Available Filament Materials</h3>    
    {% for filament_material in filament_materials%}
    {{ filament_material}}<br>
    {% endfor %}

</main>
{% endblock %}

prints/templates/prints/filament_roll_delete.html
{% extends "base.html" %}

{% block title %}Print Tracker - Delete {{ filamentroll }}{% endblock %}

{% block content %}
<main>

<h2>Delete Filament Roll</h2>
<form action="" method="post">
    {% csrf_token %}
    <p>Do you really want to delete "{{ filamentroll }}"?</p>
    <input type="submit" value="Confirm Delete" />
</form>

</main>
{% endblock %}

prints/templates/prints/manufacturer_create.html
{% extends "base.html" %}

{% block title %}Print Tracker - New Manufacturer{% endblock %}

{% block content %}
<main>

    <form action="{% url 'prints:manufacturer_new' %}" method="post">
        {% csrf_token %}
    
        {{ form.as_p }}
    
        <input type="submit" value="Create New Manufacturer" />
    </form>

</main>
{% endblock %}

prints/templates/prints/manufacturer_delete.html
{% extends "base.html" %}

{% block title %}Print Tracker - Delete Manufacturer {{ manufacturer }}{% endblock %}

{% block content %}
<main>

    <form action="" method="post">
        {% csrf_token %}
        <p>Do you really want to delete "{{ manufacturer }}"?</p>
        <input type="submit" value="Confirm Delete" />
    </form>

</main>
{% endblock %}

prints/templates/prints/manufacturer_detail.html
{% extends "base.html" %}

{% block title %}Print Tracker - {{ manufacturer }}{% endblock %}

{% block content %}
    <main>
    
        <div>
            <h2>Manufacturer: {{ manufacturer.name }}</h2>
            <a href={% url 'prints:manufacturer_edit' manufacturer.id %}>Edit Manufacturer</a><br>
            <dl>
                <dt>Number of Rolls by this Manufacturer</dt>
                <dd>{{ manufacturer.rolls.count }}</dd>
            </dl>
        </div>
        
        <div>
            {% if manufacturer.rolls.all %}
        
                <h3>Rolls</h3>

                <div class="flex-gallery">
                    {% for roll in manufacturer.rolls.all %}

                        <dl class="flex-item item">
                            <dt><a href={% url 'prints:roll_detail' roll.id %}>{{ roll }}</a></dt>
                            <dt>Number of Filament Instances</dt>
                            <dd>{{ roll.instances.count }}</dd>
                            <dt>Number of Model Prints</dt>
                            <dd><code>number_of_model_prints</code></dd>
                        </dl>

                    {% endfor %}
                </div>
                
            {% endif %}
        </div>
            
    </main>
{% endblock %}

prints/templates/prints/manufacturer_edit.html
{% extends "base.html" %}

{% block title %}Print Tracker - Edit: {{ manufacturer }}{% endblock %}

{% block content %}
    <main>

        {{ manufacturer }}<br>
        <a href={% url 'prints:manufacturer_detail' manufacturer.id %}>Cancel Edit</a><br>

        {% if manufacturer.rolls.count == 0 %}
            <a href={% url 'prints:manufacturer_delete' manufacturer.id %}>Delete Manufacturer</a><br>
        {% else %}
            <p>Manufacturer cannot be deleted since it is associated with at least one existing Filament Roll.</p>
        {% endif %}
        
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save changes to Manufacturer" />
        </form>

    </main>
{% endblock %}

prints/templates/prints/manufacturer_list.html
{% extends "base.html" %}

{% block title %}Print Tracker - Manufacturers{% endblock %}

{% block content %}
    <main class="flex-gallery">
    
        {% for manufacturer in object_list %}
    
            <div class="flex-item item">
                <a href={% url 'prints:manufacturer_detail' manufacturer.id %}>{{ manufacturer }}</a>
                <dl>
                    <dt>Number of Rolls</dt>
                    <dd>{{ manufacturer.rolls.count }}</dd>
                </dl>
            </div>
    
        {% endfor %}
    
    </main>
{% endblock %}

prints/templates/prints/model_print_list.html
{% extends "base.html" %}

{% block title %}Print Tracker - Model Prints{% endblock %}

{% block content %}
    <main class="flex-gallery">
    
        {% for model in object_list %}
    
            <div class="flex-item item">
                <a href={% url 'prints:model_detail' model.id %}>{{ model.name }}</a>
                <dl>
                    <dt>Filament Roll Used</dt>
                    <dd><a href={% url 'prints:roll_detail' model.filament_instance.filament_roll.id %}>{{ model.filament_instance.filament_roll }}</a></dd>
                    <dt>Filament Consumed</dt>
                    <dd><a href={% url 'prints:filament_instance_detail' model.filament_instance.id %}>{{ model.filament_instance }}</a></dd>
                    <dt>Model Print Creator</dt>
                    <dd>{{ model.creator.username }}</dd>
                </dl>
            </div>
    
        {% endfor %}
    
    </main>
{% endblock %}

prints/templates/prints/user_print_profile.html
{% extends "base.html" %}

{% comment %} {% block title %}Print Tracker - User Profile{% endblock %} {% endcomment %}
{% block title %}Print Tracker - User: {{ current_user.username | capfirst }}{% endblock %}

{% block content %}
    <main>
        <div>
            <h2>User Profile: {{ current_user.username | capfirst }}</h2>
            <dt>Number of Model Prints</dt>
            <dd>{{ current_user.prints.count }}</dd>
            <dt>Number of Filament Rolls</dt>
            <dd>{{ current_user.rolls.count }}</dd>
        </div>
        <div>
            <h3>Model Prints</h3>
            <div class="flex-gallery">
                {% for model_print in object_list %}

                <dl class="flex-item item">
                    <dt>Model Print</dt>
                    <dd>
                        {% if model_print %}
                        <a href={% url 'prints:model_detail' model_print.id %}>{{ model_print }}</a>
                        {% else %}
                        No Model Prints Available
                        {% endif %}
                    </dd>
                    <dt>Filament Roll Used</dt>
                    <dd><a href={% url 'prints:roll_detail' model_print.filament_instance.filament_roll.id %}>{{ model_print.filament_instance.filament_roll }}</a></dd>
                    <dt>Filament Consumed</dt>
                    <dd><a href={% url 'prints:filament_instance_detail' model_print.filament_instance.id %}>{{ model_print.filament_instance }}</a></dd>
                </dl>

                {% endfor %}
            </div>
            {{ object_list }}
        </div>

    </main>
{% endblock %}