api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views


router = DefaultRouter()
router.register('users', views.UserViewSet)
router.register('groups', views.GroupViewSet)

router.register('model-prints', views.ModelPrintViewSet)
router.register('manufacturers', views.ManufacturerViewSet)
router.register('filament-rolls', views.FilamentRollViewSet)
router.register('filament-instances', views.FilamentInstanceViewSet)
router.register('filament-materials', views.FilamentMaterialViewSet)

urlpatterns = router.urls + [

]

prints/urls.py
from django.urls import path

from . import views

app_name = 'prints'
urlpatterns = [
    #================================================================
    ## `Manufacturer` Routes:
    path(
        'manufacturers/',
        views.ManufacturerListView.as_view(),
        name='manufacturers',
    ),
    path(
        'manufacturers/<int:pk>/',
        views.ManufacturerDetailView.as_view(),
        name='manufacturer_detail'
    ),
    path(
        'manufacturers/new/',
        views.ManufacturerCreateView.as_view(),
        name='manufacturer_new'
    ),
    path(
        'manufacturers/<int:pk>/edit/',
        views.ManufacturerUpdateView.as_view(),
        name='manufacturer_edit'
    ),
    path(
        'manufacturers/<int:pk>/delete/',
        views.ManufacturerDeleteView.as_view(),
        name='manufacturer_delete'
    ),
    #================================================================
    
    
    #================================================================
    ## `FilamentMaterial` Routes:
    path(
        'filament-materials/',
        views.FilamentMaterialListView.as_view(),
        name='filament_materials',
    ),
    path(
        'filament-materials/<int:pk>/',
        views.FilamentMaterialDetailView.as_view(),
        name='filament_material_detail'
    ),
    path(
        'filament-materials/new/',
        views.FilamentMaterialCreateView.as_view(),
        name='filament_material_new'
    ),
    path(
        'filament-materials/<int:pk>/edit/',
        views.FilamentMaterialUpdateView.as_view(),
        name='filament_material_edit'
    ),
    path(
        'ilament-materials/<int:pk>/delete/',
        views.FilamentMaterialDeleteView.as_view(),
        name='filament_material_delete'
    ),
    #================================================================


    #================================================================
    ## `FilamentRoll` Routes:
    path(
        'rolls/',
        views.FilamentRollListView.as_view(),
        name='rolls',
    ),
    path(
        'rolls/<int:pk>/',
        views.FilamentRollDetailView.as_view(),
        name='roll_detail'
    ),
    path(
        'rolls/new/',
        views.FilamentRollCreateView.as_view(),
        name='roll_new'
    ),
    path(
        'rolls/<int:pk>/edit/',
        views.FilamentRollUpdateView.as_view(),
        name='roll_edit'
    ),
    path(
        'rolls/<int:pk>/delete/',
        views.FilamentRollDeleteView.as_view(),
        name='roll_delete'
    ),
    #================================================================


    #================================================================
    ## `FilamentInstance` Routes:
    path(
        'filament-instances/',
        views.FilamentInstanceListView.as_view(),
        name='filament_instances',
    ),
    path(
        'filament-instances/<int:pk>/',
        views.FilamentInstanceDetailView.as_view(),
        name='filament_instance_detail'
    ),
    path(
        'filament-instances/new/',
        views.FilamentInstanceCreateView.as_view(),
        name='filament_instance_new'
    ),
    path(
        'filament-instances/<int:pk>/edit/',
        views.FilamentInstanceUpdateView.as_view(),
        name='filament_instance_edit'
    ),
    path(
        'filament-instances/<int:pk>/delete/',
        views.FilamentInstanceDeleteView.as_view(),
        name='filament_instance_delete'
    ),
    #================================================================


    #================================================================
    ## `ModelPrint` Routes:
    path(
        'models/',
        views.ModelPrintListView.as_view(),
        name='models'
    ),
    path(
        'models/<int:pk>/',
        views.ModelPrintDetailView.as_view(),
        name='model_detail'
    ),
    path(
        'models/new/',
        views.new_model_print,
        name='model_new'
    ),
    path(
        'models/<int:pk>/edit/',
        views.ModelPrintUpdateView.as_view(),
        name='model_update'
    ),
    path(
        'models/<int:pk>/delete/',
        views.ModelPrintDeleteView.as_view(),
        name='model_delete'
    ),
    #================================================================


    #================================================================
    ## User Print Profile Routes:
    path(
        'user-print-profile/',
        views.UserPrintsProfileView.as_view(),
        name='user_print_profile'
    )
    #================================================================
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Print Tracker - Base{% endblock %}</title>
        <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css">

        {% comment %} Either of these css static location designations will work (LOCALLY) with css file location of `static/prints/css/style.css`. {% endcomment %}
        {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'prints/style.css' %}" /> {% endcomment %}
        <link rel="stylesheet" type="text/css" href="{% static 'prints/css/style.css' %}" />
        {% comment %}  {% endcomment %}

    </head>
    <body>
        <header>
            <h1>Print Tracker</h1>
            <nav>
                <h2>Development Links:</h2>
                <a
                    href="https://github.com/brucestull/three-d-print-tracker"
                    target="_blank"
                    >
                    Flynnt Knapp's Print Tracker Git Repository
                </a><br>
                <a
                    href="/api/v1/"
                    target="_blank"
                    >
                    Django REST Browsable API
                </a><br>
                <a
                    href={% url 'home' %}
                    >
                    Print Tracker - Home
                </a><br>

                
                <h2>Accounts Links:</h2>
                {% if user.is_authenticated %}
                    Who am I: {{ user.username | capfirst }}<br>
                    <a href="{% url 'logout' %}">Log Out</a><br>
                    <a href="{% url 'edit_profile' user.id %}">Edit Profile</a><br>
                    <a href="{% url 'password_change' %}">Password Change</a><br>
                    <a href="{% url 'password_reset' %}">Reset Password</a><br>
                {% else %}
                    <p>You are not logged in.</p>
                    <a href="{% url 'login' %}">Log In</a> <b>OR</b>
                    <a href="{% url 'signup' %}">Sign Up</a>
                {% endif %}


                {% if user.is_staff %}
                <h2>Staff Links:</h2>
                <a
                    href="/admin"
                    target="_blank"
                    >
                    Django Admin Interface
                </a><br>
                {% endif %}


                <h2>Application Links:</h2>
                {% if user.is_authenticated %}
                <a
                    href={% url 'prints:user_print_profile' %}
                    >
                    User Profile
                </a><br>
                <a
                    href={% url 'prints:models' %}
                    >
                    3D Model Prints
                </a><br>
                <a
                    href={% url 'prints:model_new' %}
                    >
                    Add New 3D Model Print
                </a><br>
                <a
                    href={% url 'prints:filament_instances' %}
                    >
                    Filament Instances
                </a><br>
                {% comment %} <a
                    href={% url 'prints:filament_instance_new' %}
                    >
                    Add New Filament Instance
                </a><br> {% endcomment %}
                <a
                    href={% url 'prints:rolls' %}
                    >
                    Filament Rolls
                </a><br>
                <a
                    href={% url 'prints:roll_new' %}
                    >
                    Add New Filament Roll
                </a><br>
                <a
                    href={% url 'prints:filament_materials' %}
                    >
                    Filament Materials
                </a><br>
                <a
                    href={% url 'prints:filament_material_new' %}
                    >
                    Add New Filament Material
                </a><br>
                <a
                    href={% url 'prints:manufacturers' %}
                    >
                    Manufacturers
                </a><br>
                <a
                    href={% url 'prints:manufacturer_new' %}
                    >
                    Add New Manufacturer
                </a><br>
                {% endif %}
            

            </nav>
        </header>
        {% block content %}

        {% endblock %}
    </body>
</html>

templates/model_print_create_function_based.html
{% extends "base.html" %}

{% block title %}Print Tracker - New 3D Model Print{% endblock %}

{% block content %}

<h2>Create New 3D Model Print</h2>
<form action="{% url 'prints:create_model_print' %}" method="post">
    {% csrf_token %}

    {{ model_print_form.as_p }}

    <input type="submit" value="Create New 3D Model Print" />
</form>

<h2>Create New Filament Roll</h1>
<form action="{% url 'prints:create_filament_roll' %}" method="post">
    {% csrf_token %}

    {{ filament_roll_form.as_p }}

    <input type="submit" value="Create New Filament Roll" />
</form>

{% endblock %}